name = "Some Rocks Exploded"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61e9f31073e6139c81dcc9a1ecbc14b7618ef422532d5167244df22bfe20bfd9"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
