name = "Some Rocks Exploded"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "951e9775efa39290d4d4d953a2a043ee83dc914143ff260cbcd5df151ed504cc"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
