name = "Some Rocks Exploded"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4fcdbc7b057250da983e6012ad0904560c5be8f77e9482c158c93337a5d4a9b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
