name = "Some Rocks Exploded"
author = "wozeparrot"
version = "1.0.0-alpha"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1291df9ecf9fc5b7065a71a5d0366c834255b70d3ada878f529a632384812bc5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
