name = "Some Rocks Exploded"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2d4366756bb64c806fd141eb97bbc0d4445a798ea160b0cae33bb7625374906"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
