# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				spawner_minecart = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				salmon = true
				piglin_brute = true
				goat = true
				furnace_minecart = true
				item_frame = true
				horse = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				blaze = true
				end_crystal = true
				endermite = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				illusioner = true
				eye_of_ender = true
				villager = true
				wolf = true
				zombie_villager = true
				elder_guardian = true
				boat = true
				polar_bear = true
				strider = true
				hopper_minecart = true
				falling_block = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				command_block_minecart = true

			[light_sources.settings.entities.kibe]
				thrown_torch = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				naga = true

			[light_sources.settings.entities.blast]
				dirt_trigger_bomb = true
				pearl_trigger_bomb = true
				confetti_bomb = true
				stripminer = true
				gunpowder_block = true
				cold_digger = true
				naval_mine = true
				diamond_bomb = true
				bomb = true
				diamond_trigger_bomb = true

