name = "Additional Additions"
filename = "AdditionalAdditions-3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3555/370/AdditionalAdditions-3.0.1.jar"
hash-format = "murmur2"
hash = "2555103968"

[update]
[update.curseforge]
file-id = 3555370
project-id = 508556
