name = "AE2 Things"
filename = "AE2Things-1.0.1-beta.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3635/67/AE2Things-1.0.1-beta.4.jar"
hash-format = "murmur2"
hash = "2779522296"

[update]
[update.curseforge]
file-id = 3635067
project-id = 563800
