name = "Alloy Forgery"
filename = "wraith-alloy-forgery-2.0.9+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/653/wraith-alloy-forgery-2.0.9+1.18.jar"
hash-format = "murmur2"
hash = "1661760722"

[update]
[update.curseforge]
file-id = 3629653
project-id = 438718
