name = "Applied Energistics 2"
filename = "appliedenergistics2-10.1.0-beta.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/573/appliedenergistics2-10.1.0-beta.1.jar"
hash-format = "murmur2"
hash = "4052197219"

[update]
[update.curseforge]
file-id = 3630573
project-id = 223794
