name = "Arcanus"
filename = "arcanus-1.27.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/99/arcanus-1.27.jar"
hash-format = "murmur2"
hash = "2534357293"

[update]
[update.curseforge]
file-id = 3625099
project-id = 517833
