name = "Architectury API (Fabric)"
filename = "architectury-3.6.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/940/architectury-3.6.14.jar"
hash-format = "murmur2"
hash = "3111157018"

[update]
[update.curseforge]
file-id = 3631940
project-id = 419697
