name = "Architectury API (Fabric)"
filename = "architectury-3.5.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/998/architectury-3.5.12.jar"
hash-format = "murmur2"
hash = "3442069832"

[update]
[update.curseforge]
file-id = 3629998
project-id = 419697
