name = "Artisanat"
filename = "artisanat-2.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/56/artisanat-2.2.1.jar"
hash-format = "murmur2"
hash = "3932130990"

[update]
[update.curseforge]
file-id = 3575056
project-id = 399443
