name = "AttributeFix"
filename = "AttributeFix-Fabric-1.18.1-13.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/618/AttributeFix-Fabric-1.18.1-13.0.5.jar"
hash-format = "murmur2"
hash = "598835176"

[update]
[update.curseforge]
file-id = 3615618
project-id = 280510
