name = "Balm (Fabric Edition)"
filename = "balm-fabric-2.4.1+0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/151/balm-fabric-2.4.1+0.jar"
hash-format = "murmur2"
hash = "277662906"

[update]
[update.curseforge]
file-id = 3606151
project-id = 500525
