name = "BCLib"
filename = "bclib-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/567/bclib-1.3.1.jar"
hash-format = "murmur2"
hash = "736947709"

[update]
[update.curseforge]
file-id = 3637567
project-id = 495191
