name = "BetterNether"
filename = "better-nether-6.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/290/better-nether-6.0.10.jar"
hash-format = "murmur2"
hash = "2405044414"

[update]
[update.curseforge]
file-id = 3636290
project-id = 311377
