name = "BetterNether"
filename = "better-nether-6.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/671/better-nether-6.0.9.jar"
hash-format = "murmur2"
hash = "3519080257"

[update]
[update.curseforge]
file-id = 3613671
project-id = 311377
