name = "BetterEnd"
filename = "better-end-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/291/better-end-1.0.2.jar"
hash-format = "murmur2"
hash = "2415918512"

[update]
[update.curseforge]
file-id = 3636291
project-id = 413596
