name = "Boat Item View"
filename = "Boat-Item-View-Fabric-1.18-0.0.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BdKIyOLe/versions/1.18-0.0.3-fabric/Boat-Item-View-Fabric-1.18-0.0.3.jar"
hash-format = "sha512"
hash = "a83fe6c4ff20591981119ce1023afdd8f75d2ff3a9e62244de6cead2ac85d10cd784dd89e4a5798d678196daa9a3d1ac00bb820d500f6c26a798d86e998cb8e7"

[update]
[update.modrinth]
mod-id = "BdKIyOLe"
version = "n8Cenodv"
