name = "Campanion"
filename = "campanion-3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/521/campanion-3.0.2.jar"
hash-format = "murmur2"
hash = "3773304072"

[update]
[update.curseforge]
file-id = 3613521
project-id = 373138
