name = "Chipped"
filename = "chipped-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/249/chipped-1.2.jar"
hash-format = "murmur2"
hash = "830326087"

[update]
[update.curseforge]
file-id = 3606249
project-id = 456956
