name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18-FABRIC-1.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/391/Croptopia-1.18-FABRIC-1.8.0.jar"
hash-format = "murmur2"
hash = "1696913573"

[update]
[update.curseforge]
file-id = 3590391
project-id = 415438
