name = "Culinaire"
filename = "culinaire-2.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/39/culinaire-2.3.3.jar"
hash-format = "murmur2"
hash = "752474461"

[update]
[update.curseforge]
file-id = 3575039
project-id = 390675
