name = "DashLoader"
filename = "dashloader-def-3.0-rc14-1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3619/672/dashloader-def-3.0-rc14-1.18.jar"
hash-format = "murmur2"
hash = "1447311632"

[update]
[update.curseforge]
file-id = 3619672
project-id = 472772
