name = "[FABRIC] Launchpads"
filename = "zihlaunchpads-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3581/664/zihlaunchpads-1.2.0.jar"
hash-format = "murmur2"
hash = "3291583218"

[update]
[update.curseforge]
file-id = 3581664
project-id = 521065
