name = "Fabric Waystones"
filename = "wraith-waystones-2.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/744/wraith-waystones-2.4.1.jar"
hash-format = "murmur2"
hash = "2491584330"

[update]
[update.curseforge]
file-id = 3575744
project-id = 410902
