name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.6.1_MC_1.18-1.18.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3631/897/fancymenu_fabric_2.6.1_MC_1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "4256963472"

[update]
[update.curseforge]
file-id = 3631897
project-id = 416796
