name = "FerriteCore"
filename = "ferritecore-4.1.0-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/uXXizFIs/versions/4.1.0/ferritecore-4.1.0-fabric.jar"
hash-format = "sha512"
hash = "51ff2b780266659ea830b85dd82db5c9d62fb71f5678cd2ca04809ea49e52157177db70130cbe31a095ff1c7e9c2e2edcaa32cd9b5f73dff4e90152c652b03ac"

[update]
[update.modrinth]
mod-id = "uXXizFIs"
version = "OhmGV4Hp"
