name = "FTB Quests (Fabric)"
filename = "ftb-quests-fabric-1801.3.7-build.93.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/554/ftb-quests-fabric-1801.3.7-build.93.jar"
hash-format = "murmur2"
hash = "1499827733"

[update]
[update.curseforge]
file-id = 3627554
project-id = 438496
