name = "FTB Quests (Fabric)"
filename = "ftb-quests-fabric-1801.3.7-build.91.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3617/220/ftb-quests-fabric-1801.3.7-build.91.jar"
hash-format = "murmur2"
hash = "2902802102"

[update]
[update.curseforge]
file-id = 3617220
project-id = 438496
