name = "Industrial Revolution"
filename = "indrev-1.13.6-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/880/indrev-1.13.6-BETA.jar"
hash-format = "murmur2"
hash = "3257438632"

[update]
[update.curseforge]
file-id = 3599880
project-id = 391708
