name = "Inf Chest"
filename = "InfChest-18.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/610/InfChest-18.2-fabric.jar"
hash-format = "murmur2"
hash = "3030740418"

[update]
[update.curseforge]
file-id = 3637610
project-id = 312222
