name = "Inmis"
filename = "inmis-2.5.1-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/328/inmis-2.5.1-1.18.1.jar"
hash-format = "murmur2"
hash = "2432394544"

[update]
[update.curseforge]
file-id = 3623328
project-id = 369254
