name = "Item Scroller"
filename = "itemscroller-fabric-1.18.1-0.15.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/858/itemscroller-fabric-1.18.1-0.15.0.jar"
hash-format = "murmur2"
hash = "1486580764"

[update]
[update.curseforge]
file-id = 3615858
project-id = 242064
