name = "Kibe Utilities"
filename = "kibe-1.9.4-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3524/209/kibe-1.9.4-BETA+1.18.jar"
hash-format = "murmur2"
hash = "1566732787"

[update]
[update.curseforge]
file-id = 3524209
project-id = 388832
