name = "Konkrete [Fabric]"
filename = "konkrete_fabric_1.3.3_MC_1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3593/183/konkrete_fabric_1.3.3_MC_1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "2428366703"

[update]
[update.curseforge]
file-id = 3593183
project-id = 416797
