name = "KubeJS (Fabric)"
filename = "kubejs-fabric-1801.4.2-build.283.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/455/kubejs-fabric-1801.4.2-build.283.jar"
hash-format = "murmur2"
hash = "672323002"

[update]
[update.curseforge]
file-id = 3627455
project-id = 395864
