name = "Lib Block Attributes"
filename = "libblockattributes-all-0.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/966/libblockattributes-all-0.10.0.jar"
hash-format = "murmur2"
hash = "54038927"

[update]
[update.curseforge]
file-id = 3540966
project-id = 317995
