name = "Load My Resources [Fabric]"
filename = "loadmyresources_fabric_1.0.1-1_MC_1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3545/317/loadmyresources_fabric_1.0.1-1_MC_1.18.jar"
hash-format = "murmur2"
hash = "2202795304"

[update]
[update.curseforge]
file-id = 3545317
project-id = 534835
