name = "megane"
filename = "megane-7.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3634/796/megane-7.1.0.jar"
hash-format = "murmur2"
hash = "1183544241"

[update]
[update.curseforge]
file-id = 3634796
project-id = 408118
