name = "Modern Industrialization"
filename = "Modern-Industrialization-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/287/Modern-Industrialization-1.0.4.jar"
hash-format = "murmur2"
hash = "433630637"

[update]
[update.curseforge]
file-id = 3595287
project-id = 405388
