name = "Mythic Metals"
filename = "mythicmetals-0.11.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/448/mythicmetals-0.11.4.jar"
hash-format = "murmur2"
hash = "300443386"

[update]
[update.curseforge]
file-id = 3631448
project-id = 410127
