name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh The Biomes You'll Go-fabric-1.18.1-1.3.5.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/348/Oh The Biomes You'll Go-fabric-1.18.1-1.3.5.8.jar"
hash-format = "murmur2"
hash = "787128269"

[update]
[update.curseforge]
file-id = 3627348
project-id = 391378
