name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.5.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/599/owo-lib-0.5.1+1.18.jar"
hash-format = "murmur2"
hash = "1956556448"

[update]
[update.curseforge]
file-id = 3629599
project-id = 532610
