name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.18.1-1.2.10.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.18-1.2.10/plasmovoice-fabric-1.18.1-1.2.10.jar"
hash-format = "sha512"
hash = "93c0af1b09ae781c78901e1b8f0934defc6ab1f8c4d06073d76c254a1d30382522fcae04efa10904365ddb19ac8977617eec3330404d3bb4c53e64d05f8e80cb"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "GDqzd1zx"
