name = "Reborn Core"
filename = "RebornCore-5.1.0-beta.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/978/RebornCore-5.1.0-beta.8.jar"
hash-format = "murmur2"
hash = "3400552887"

[update]
[update.curseforge]
file-id = 3631978
project-id = 237903
