name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-3.3.7+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/954/repurposed_structures_fabric-3.3.7+1.18.1.jar"
hash-format = "murmur2"
hash = "290377099"

[update]
[update.curseforge]
file-id = 3636954
project-id = 391366
