name = "Rhino"
filename = "rhino-fabric-1800.1.7-build.94.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/722/rhino-fabric-1800.1.7-build.94.jar"
hash-format = "murmur2"
hash = "495140503"

[update]
[update.curseforge]
file-id = 3604722
project-id = 416294
