name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.2.409.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3625/853/RoughlyEnoughItems-7.2.409.jar"
hash-format = "murmur2"
hash = "917880681"

[update]
[update.curseforge]
file-id = 3625853
project-id = 310111
