name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.2.422.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3637/406/RoughlyEnoughItems-7.2.422.jar"
hash-format = "murmur2"
hash = "1699337723"

[update]
[update.curseforge]
file-id = 3637406
project-id = 310111
