name = "Seamless Loading Screen"
filename = "seamless-loading-screen-1.3.6+1.18.jar"
side = "client"

[download]
url = "https://github.com/cm-360/Seamless-Loading-Screen/releases/download/v1.3.6%2B1.18/seamless-loading-screen-1.3.6+1.18.jar"
hash-format = "sha256"
hash = "d46ecf44a8428dc8241dc20b554ea57d951a6d33c016e9e1ee0072a14d3c2af8"
