name = "Secret Rooms Fabric"
filename = "secretrooms-1.2.0+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/634/secretrooms-1.2.0+1.18.1.jar"
hash-format = "murmur2"
hash = "4240526958"

[update]
[update.curseforge]
file-id = 3592634
project-id = 359248
