name = "slotlink"
filename = "slotlink-4.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/834/slotlink-4.1.0.jar"
hash-format = "murmur2"
hash = "864703922"

[update]
[update.curseforge]
file-id = 3615834
project-id = 391014
