name = "Stemaria [FORGE/FABRIC]"
filename = "%5BFABRIC%5D-Stemaria-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/67/%5BFABRIC%5D-Stemaria-1.1.2.jar"
hash-format = "murmur2"
hash = "3460953095"

[update]
[update.curseforge]
file-id = 3622067
project-id = 496756
