name = "Tech Reborn"
filename = "TechReborn-5.1.0-beta.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/811/TechReborn-5.1.0-beta.7.jar"
hash-format = "murmur2"
hash = "987967881"

[update]
[update.curseforge]
file-id = 3626811
project-id = 233564
