name = "The Corners"
filename = "the-corners-1.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/825/the-corners-1.1.5.jar"
hash-format = "murmur2"
hash = "402381915"

[update]
[update.curseforge]
file-id = 3630825
project-id = 523644
