name = "Things [Fabric]"
filename = "things-0.2.14+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/572/things-0.2.14+1.18.jar"
hash-format = "murmur2"
hash = "2749271292"

[update]
[update.curseforge]
file-id = 3631572
project-id = 456151
