name = "Things [Fabric]"
filename = "things-0.2.13+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/607/things-0.2.13+1.18.jar"
hash-format = "murmur2"
hash = "4053205706"

[update]
[update.curseforge]
file-id = 3629607
project-id = 456151
