name = "Things [Fabric]"
filename = "things-0.2.12+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/689/things-0.2.12+1.18.jar"
hash-format = "murmur2"
hash = "2123139810"

[update]
[update.curseforge]
file-id = 3604689
project-id = 456151
