name = "Trinkets (Fabric)"
filename = "trinkets-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/559/trinkets-3.2.0.jar"
hash-format = "murmur2"
hash = "5469540"

[update]
[update.curseforge]
file-id = 3629559
project-id = 341284
