name = "WTHIT"
filename = "wthit-fabric-4.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3635/138/wthit-fabric-4.5.1.jar"
hash-format = "murmur2"
hash = "2703601993"

[update]
[update.curseforge]
file-id = 3635138
project-id = 440979
