name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.2.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/249/youre-in-grave-danger-1.2.14.jar"
hash-format = "murmur2"
hash = "737863220"

[update]
[update.curseforge]
file-id = 3623249
project-id = 544912
